/** Permissions of the users */
export const Permission = {
    VIEW_LOGIN: 'VIEW_LOGIN',
    VIEW_CART: 'VIEW_CART',
    ADD_RESTAURANT: 'ADD_RESTAURANT',
    OPEN_RESTAURANT: 'OPEN_RESTAURANT',
    EDIT_RESTAURANT: 'EDIT_RESTAURANT',
    DELETE_RESTAURANT: 'DELETE_RESTAURANT',
    ADD_TO_CART: 'ADD_TO_CART',
    ADD_MENU_ITEM: 'ADD_MENU_ITEM',
    EDIT_MENU_ITEM: 'EDIT_MENU_ITEM',
    DELETE_MENU_ITEM: 'DELETE_MENU_ITEM',
} as const;
