export const Permission = {
    VIEW_LOGIN: 'VIEW_LOGIN',
    VIEW_CART: 'VIEW_CART',
    ADD_RESTAURANT: 'ADD_RESTAURANT',
    OPEN_RESTAURANT: 'OPEN_RESTAURANT',
    EDIT_RESTAURANT: 'EDIT_RESTAURANT',
    DELETE_RESTAURANT: 'DELETE_RESTAURANT',
} as const;
